#!/bin/bash

timestamp_() {
 date +'%H:%M:%S'
}

message_() {
  local message="${1}"
  local log="${2}"

  echo "$(timestamp_) <[36m${USER}[0m> ${message}" >> "${log}"
}

action_() {
  local message="${1}"
  local log="${2}"

  echo "$(timestamp_) * ${USER} ${message}" >> "${log}"
}


make_log() {
  local log="${1}"

  if [ -f "${log}" ]; then
    return
  fi

  local dir="$(dirname "${log}")"
  mkdir -p "${dir}"
  touch "${log}"
  chmod 666 "${log}"
}

watch_log() {
  local log="${1}"

  tail -n 1000 -f "${log}" | sed "s/\[36m${USER}/\[38;1m${USER}/"
}

write_log() {
  local log="${1}"

  action_ "joined." "${log}"
  trap "action_ 'left.' '${log}'; kill ${PPID}" SIGINT

  local channel="$(basename "${log}")"
  while true; do
    read -p "[#[36m${channel}[0m [38;1m${USER}[0m] "
    message_ "${REPLY}" "${log}"
    clear
  done
}


main() {
  local this="${0}"
  local param="${1}"

  if [ ${param} == 'command_' ]; then
    local cmd="${2}"
    local log="${3}"
    "${cmd}" "${log}"
  fi

  local dir='/tmp/.localchat'
  local log="${dir}/main"
  if [ -n "${param}" ]; then
    log="${dir}/${param}"
  fi
  make_log "${log}"

  splitvt -norc -bottom -s 1000 -t "OI" \
    -upper "${this} command_ watch_log ${log}" \
    -lower "${this} command_ write_log ${log}"
}


main "${@}"
